---
title: "Predicting the Quality of a Workout"
author: "Ben Kling"
date: "4/15/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(parallel)
library(doParallel)
library(randomForest)
```

## Title goes here

```{r file download and data frame initialization}
# Download the training file
if(!file.exists("pml-training.csv")) download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv","pml-training.csv")
# Download the test file
if(!file.exists("pml-testing.csv")) download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv","pml-testing.csv")

# establish data frame
trainingraw <- read_csv("pml-training.csv")
testingraw <- read_csv("pml-testing.csv")

```

```{r data cleaning}

# #DIV/0! values
training <- trainingraw %>%
    mutate(across(.fns=na_if, y="#DIV/0!")) %>% # lots of "#DIV/0" errors in the data (excel output?)
    mutate(across(.cols = -c(1:7,160), .fns = as.numeric)) %>% # Coerce to numeric
    mutate(across(.cols = -c(1:7,160), .fns = replace_na, replace=0)) %>% # zero out the NA values
    filter(!is.na(classe)) %>% # remove NA classe values
    mutate(classe = as.factor(classe)) # convert classe to a factor



# these features have no non-zero values
allzero <- c('kurtosis_yaw_belt',
             'skewness_yaw_belt', 
             'amplitude_yaw_belt', 
             'kurtosis_yaw_dumbbell', 
             'skewness_yaw_dumbbell', 
             'amplitude_yaw_dumbbell', 
             'kurtosis_yaw_forearm', 
             'skewness_yaw_forearm', 
             'amplitude_yaw_forearm')

training <- training %>%
    select(-allzero)

# first 7 variables are not measurements, merely attributes and can be ignored
trainingfeatures <- training %>% select(-(1:7)) 

```

```{r eda plots}

g <- ggplot(training, mapping = aes(max_roll_belt, fill=classe, color=classe))
g + geom_histogram()
g + geom_histogram() + facet_wrap(~classe)
```

```{r eda and qa slicing}

for (var in allzero) {
    checkzero %>%
        group_by(.data[[var]]) %>% 
        summarize(ct = n()) %>%
        head(n=12) %>%
        print()
}

```

```{r model selection}

# apply pca
# run random forest on the reduced feature set
# parallellize the execution

set.seed(1234) #set a seed for reproducibility

cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

fitCtrl <- trainControl(method='cv',
                        number=5,
                        allowParallel=TRUE)

rfmodel <- train(classe ~.,
                 data=trainingfeatures,
                 method='rf',
                 trControl=fitCtrl)

stopCluster(cluster)
registerDoSEQ()
```


```{r model evaluation}

rfmodel 

rfmodel$resample

confusionMatrix.train(rfmodel)

```


### Citation

All data in this analysis was made available here: <https://web.archive.org/web/20161224072740/http:/groupware.les.inf.puc-rio.br/har>
